FROM python:3.9-alpine
WORKDIR /prod

COPY requirements.txt .


RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps



COPY . .

CMD python3 -u server.py